import type { ControlDef } from '../core/state.ts';
import { themeOptions } from './themes.ts';
import { patternOptions, RD_PATTERNS } from '../modes2d/patterns.ts';

// Modes that share the generic Warp/Scale controls (the procedural fields).
const WARP_MODES = ['raymarch', 'flow', 'cells', 'mandala'];
const SCALE_MODES = [
  'waveform',
  'raymarch',
  'flow',
  'cells',
  'logo',
  'trails3d',
  'magneto',
  'mandala',
  'sand',
];

/**
 * THE uniform schema — single source of truth.
 *
 * Each entry generates both a panel widget (ControlPanel, per `type`) and a
 * shader uniform declaration + per-frame upload (Renderer). `type` defaults to
 * `'slider'`. `modes`/`pass` scope a control's visibility (see ControlDef): a
 * control shows only when its mode is active / its pass is enabled, so the panel
 * always reflects what's actually steerable right now. The uniform is declared
 * and uploaded regardless.
 *
 * Per-mode controls are grouped at the end so each mode has an expressive,
 * distinctive set on top of the shared Gain/Warp/Scale.
 */
export const CONTROLS: ControlDef[] = [
  // --- Shared --------------------------------------------------------------
  {
    id: 'gain',
    name: 'Gain',
    glslName: 'uGain',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.5,
  },
  {
    // Read only by present.frag — resolves the HDR chain output for display.
    id: 'tonemap',
    name: 'Tonemap',
    glslName: 'uTonemap',
    type: 'select',
    options: [
      { label: 'None', value: 0 },
      { label: 'Reinhard', value: 1 },
      { label: 'ACES', value: 2 },
    ],
    default: 0,
  },
  {
    // The instrument's global colour: which theme, and how far every mode is
    // pulled toward it (0 = each mode's own palette, 1 = fully re-tinted).
    // Keys 1-5 switch themes; the colours themselves ride in uThemeA/B/C.
    id: 'theme',
    name: 'Theme',
    glslName: 'uTheme',
    type: 'select',
    options: themeOptions(),
    default: 0,
  },
  {
    id: 'themeMix',
    name: 'Tint',
    glslName: 'uThemeMix',
    min: 0,
    max: 1,
    step: 0.01,
    // High by default: at 0.85 a theme actually reads as itself while a trace
    // of each mode's own colour survives. Pull it down for the native look.
    default: 0.85,
  },
  {
    id: 'warp',
    name: 'Warp',
    glslName: 'uWarp',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.4,
    modes: WARP_MODES,
  },
  {
    id: 'scale',
    name: 'Scale',
    glslName: 'uScale',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.4,
    modes: SCALE_MODES,
  },

  // --- Per-mode (distinctive) ---------------------------------------------
  {
    id: 'barCount',
    name: 'Bar Count',
    glslName: 'uBarCount',
    min: 8,
    max: 48,
    step: 1,
    default: 28,
    modes: ['bars'],
  },
  {
    id: 'barGlow',
    name: 'Bar Glow',
    glslName: 'uBarGlow',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.45,
    modes: ['bars'],
  },
  {
    id: 'waveStyle',
    name: 'Trace',
    glslName: 'uWaveStyle',
    type: 'select',
    options: [
      { label: 'Line', value: 0 },
      { label: 'Mirror', value: 1 },
      { label: 'Radial', value: 2 },
    ],
    default: 1,
    modes: ['waveform'],
  },
  {
    id: 'waveAmp',
    name: 'Amplitude',
    glslName: 'uWaveAmp',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.55,
    modes: ['waveform'],
  },
  {
    id: 'waveGlow',
    name: 'Glow',
    glslName: 'uWaveGlow',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.45,
    modes: ['waveform'],
  },
  {
    id: 'waveLayers',
    name: 'Echoes',
    glslName: 'uWaveLayers',
    min: 1,
    max: 6,
    step: 1,
    default: 3,
    modes: ['waveform'],
  },
  {
    // Named regimes. Declared before Feed/Kill on purpose: picking one writes
    // them through an onChange listener, and recalling a preset applies values
    // in schema order — so the pattern lands first and a preset's hand-tuned
    // Feed/Kill override it, rather than the other way round.
    id: 'rdPattern',
    name: 'Pattern',
    glslName: 'uRdPattern',
    type: 'select',
    options: patternOptions(),
    default: 0,
    modes: ['reaction'],
  },
  {
    // Simulation height in cells. Gray-Scott features are a fixed number of
    // cells wide, so this is literally line thickness: more cells, finer lines.
    id: 'rdDetail',
    name: 'Detail',
    glslName: 'uRdDetail',
    type: 'select',
    options: [
      { label: 'Coarse', value: 384 },
      { label: 'Fine', value: 720 },
      { label: 'Ultra', value: 1080 },
    ],
    default: 720,
    modes: ['reaction'],
  },
  {
    // Gray-Scott's two parameters. The living region is narrow — outside it
    // the pattern either dies out or floods — so the ranges here are the
    // usable window, not the mathematical one (Pearson/Munafo, REFERENCES.md).
    id: 'rdFeed',
    name: 'Feed',
    glslName: 'uRdFeed',
    min: 0.02,
    max: 0.07,
    step: 0.0005,
    default: RD_PATTERNS[0].feed,
    modes: ['reaction'],
  },
  {
    id: 'rdKill',
    name: 'Kill',
    glslName: 'uRdKill',
    min: 0.05,
    max: 0.07,
    step: 0.0005,
    default: RD_PATTERNS[0].kill,
    modes: ['reaction'],
  },
  {
    id: 'rdMirror',
    name: 'Symmetry',
    glslName: 'uRdMirror',
    type: 'select',
    options: [
      { label: 'Free', value: 0 },
      { label: 'Inkblot', value: 1 },
      { label: 'Quad', value: 2 },
    ],
    default: 0,
    modes: ['reaction'],
  },
  {
    id: 'rdSpeed',
    name: 'Growth',
    glslName: 'uRdSpeed',
    min: 2,
    max: 24,
    step: 1,
    default: 12,
    modes: ['reaction'],
  },
  {
    id: 'rdAudio',
    name: 'Chem Drive',
    glslName: 'uRdAudio',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.6,
    modes: ['reaction'],
  },
  {
    // 0 = the old single cosine ramp, 1 = full thin-film sheen.
    id: 'rayIris',
    name: 'Iridescence',
    glslName: 'uRayIris',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.85,
    modes: ['raymarch'],
  },
  {
    id: 'rayGlow',
    name: 'Glow',
    glslName: 'uRayGlow',
    min: 0,
    max: 2,
    step: 0.01,
    default: 1.0,
    modes: ['raymarch'],
  },
  {
    id: 'flowTurb',
    name: 'Turbulence',
    glslName: 'uFlowTurb',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.4,
    modes: ['flow'],
  },
  {
    id: 'mandalaSegs',
    name: 'Wedges',
    glslName: 'uMandalaSegs',
    min: 2,
    max: 16,
    step: 1,
    default: 8,
    modes: ['mandala'],
  },
  {
    // How far the kick and bass push the kaliset's shape parameter — the
    // pattern re-cuts rather than just brightening.
    id: 'mandalaFold',
    name: 'Fold',
    glslName: 'uMandalaFold',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.5,
    modes: ['mandala'],
  },
  {
    id: 'sandGrain',
    name: 'Grain',
    glslName: 'uSandGrain',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.5,
    modes: ['sand'],
  },
  {
    id: 'sandSpread',
    name: 'Spread',
    glslName: 'uSandSpread',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.35,
    modes: ['sand'],
  },
  {
    id: 'cellEdge',
    name: 'Edge Glow',
    glslName: 'uCellEdge',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.5,
    modes: ['cells'],
  },
  {
    // Particle texture size: count = value². The mode's perf story — drop it
    // on weak GPUs, raise it for density.
    id: 'particles',
    name: 'Particles',
    glslName: 'uParticles',
    type: 'select',
    options: [
      { label: '16k', value: 128 },
      { label: '65k', value: 256 },
      { label: '262k', value: 512 },
    ],
    default: 256,
    modes: ['trails3d', 'magneto'],
  },
  {
    // Magnetosphere's physics: how hard the poles pull, and how much momentum
    // survives each step. Damping is the difference between a swarm and an
    // explosion — the single most sensitive number in the mode.
    id: 'magCharge',
    name: 'Charge',
    glslName: 'uMagCharge',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.65,
    modes: ['magneto'],
  },
  {
    id: 'magDamp',
    name: 'Momentum',
    glslName: 'uMagDamp',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.62,
    modes: ['magneto'],
  },
  {
    id: 'magSpin',
    name: 'Pole Orbit',
    glslName: 'uMagSpin',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.4,
    modes: ['magneto'],
  },
  {
    // The iTunes 10 Magnetosphere's two backdrop elements.
    id: 'magNebula',
    name: 'Nebula',
    glslName: 'uMagNebula',
    min: 0,
    max: 1,
    step: 0.01,
    // Clouds are a backdrop; below ~0.8 they vanish behind the swarm entirely.
    default: 0.85,
    modes: ['magneto'],
  },
  {
    id: 'magRays',
    name: 'Rays',
    glslName: 'uMagRays',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.6,
    modes: ['magneto'],
  },
  {
    id: 'flowSpeed',
    name: 'Flow',
    glslName: 'uFlowSpeed',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.5,
    modes: ['trails3d'],
  },
  {
    id: 'trailTurb',
    name: 'Turbulence',
    glslName: 'uTrailTurb',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.4,
    modes: ['trails3d'],
  },
  {
    id: 'logoRipple',
    name: 'Ripple',
    glslName: 'uLogoRipple',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.5,
    modes: ['logo'],
  },

  // --- Post-pass controls (shown only while their pass is enabled) ---------
  {
    // MilkDrop's warp vocabulary (see passes/warp.frag). Defaults are Geiss's:
    // zoom 1.0 = still, warp 1.0 = normal, decay 0.98 recommended.
    id: 'warpZoom',
    name: 'Warp Zoom',
    glslName: 'uWarpZoom',
    min: 0.9,
    max: 1.1,
    step: 0.001,
    default: 1.012,
    pass: 'warp',
  },
  {
    id: 'warpRot',
    name: 'Warp Rotate',
    glslName: 'uWarpRot',
    min: -1,
    max: 1,
    step: 0.01,
    default: 0.18,
    pass: 'warp',
  },
  {
    id: 'warpAmount',
    name: 'Warp',
    glslName: 'uWarpAmount',
    min: 0,
    max: 2,
    step: 0.01,
    default: 1.0,
    pass: 'warp',
  },
  {
    id: 'warpDecay',
    name: 'Warp Decay',
    glslName: 'uWarpDecay',
    min: 0.7,
    max: 0.995,
    step: 0.001,
    // Geiss recommends 0.98, but MilkDrop draws sparse geometry into its
    // feedback buffer; FLUX feeds it a full-screen mode, and above ~0.95 every
    // pixel keeps getting re-lit until the image washes out. 0.90 keeps the
    // mode's structure with the outward pull on top.
    default: 0.9,
    pass: 'warp',
  },
  {
    id: 'warpAudio',
    name: 'Warp Drive',
    glslName: 'uWarpAudio',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.6,
    pass: 'warp',
  },
  {
    id: 'trailDecay',
    name: 'Trail Decay',
    glslName: 'uTrailDecay',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.9,
    pass: 'trails',
  },
  {
    id: 'ditherMode',
    name: 'Dither Noise',
    glslName: 'uDitherMode',
    type: 'select',
    options: [
      { label: 'Bayer', value: 0 },
      { label: 'IGN', value: 1 },
      { label: 'Blue Noise', value: 2 },
    ],
    default: 0,
    pass: 'dither',
  },
  {
    id: 'ditherTemporal',
    name: 'Animate Noise',
    glslName: 'uDitherTemporal',
    type: 'toggle',
    default: false,
    pass: 'dither',
  },
  {
    // Bayer matrix size — no effect on the IGN / blue-noise modes.
    id: 'ditherSize',
    name: 'Dither Matrix',
    glslName: 'uDitherSize',
    type: 'select',
    options: [
      { label: '2', value: 2 },
      { label: '4', value: 4 },
      { label: '8', value: 8 },
    ],
    default: 4,
    pass: 'dither',
  },
  {
    id: 'ditherLevels',
    name: 'Dither Levels',
    glslName: 'uDitherLevels',
    min: 2,
    max: 8,
    step: 1,
    default: 4,
    pass: 'dither',
  },
  {
    // 0 = no bright-pass (fully energy-conserving mip bloom); >0 = soft knee.
    id: 'bloomThreshold',
    name: 'Bloom Threshold',
    glslName: 'uBloomThreshold',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0,
    pass: 'bloom',
  },
  {
    id: 'bloomIntensity',
    name: 'Bloom Intensity',
    glslName: 'uBloomIntensity',
    min: 0,
    max: 3,
    step: 0.01,
    default: 0.8,
    pass: 'bloom',
  },
  {
    id: 'bloomRadius',
    name: 'Bloom Radius',
    glslName: 'uBloomRadius',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.35,
    pass: 'bloom',
  },
  {
    id: 'tunnelSpeed',
    name: 'Tunnel Speed',
    glslName: 'uTunnelSpeed',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.35,
    pass: 'tunnel',
  },
  {
    id: 'tunnelTwist',
    name: 'Tunnel Twist',
    glslName: 'uTunnelTwist',
    min: -1,
    max: 1,
    step: 0.01,
    default: 0.3,
    pass: 'tunnel',
  },
  {
    id: 'tunnelRepeat',
    name: 'Tunnel Wraps',
    glslName: 'uTunnelRepeat',
    min: 1,
    max: 4,
    step: 1,
    default: 2,
    pass: 'tunnel',
  },
  {
    id: 'kaleidoSegments',
    name: 'Kaleido Segments',
    glslName: 'uKaleidoSegments',
    min: 2,
    max: 16,
    step: 1,
    default: 6,
    pass: 'kaleido',
  },
  {
    id: 'scanlineIntensity',
    name: 'Scanline / VHS',
    glslName: 'uScanlineIntensity',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.5,
    pass: 'scanline',
  },
];
